version: '3'

services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controlefinanceiro
    volumes:
    - ./mysqldata:/var/lib/mysql
    ports:
    - "3306:3306"
